name: season
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flrx_validator: ^0.6.0
  quiver: ^3.2.1
  google_fonts: ^6.1.0
  image_picker: ^0.8.7+5
  cached_network_image: ^3.2.3
  curved_navigation_bar: ^1.0.3
  get: ^4.6.6
  # easy_localization: ^3.0.3
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  loading_indicator: ^3.1.1
  firebase_messaging: ^14.7.2
  url_launcher: ^6.1.14
  cloud_firestore: ^4.12.1
  firebase_auth: ^4.12.0
  google_sign_in: ^6.1.5
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/image/
    - assets\Policy_Json\policy_ar.json
    - assets\Policy_Json\policy_en.json

